# -*- coding: utf-8 -*-
# "DNA" dos relatórios: seções e campos de cada tipo.
# Formato de cada campo: ("chave_no_banco", "Rótulo escrito na planilha")

# ============================================================
# LEGENDA DE UNIDADES (aba da planilha -> nome oficial)
# ============================================================
UNIDADES = {
    "cras": {
        "CEC": "CRAS Cecap",
        "CEN": "CRAS Central",
        "CR": "CRAS Cruzeiro do Sul",
        "HO": "CRAS Hortênsias",
        "ML": "CRAS Maria Luiza",
        "PSP": "CRAS Parque São Paulo",
        "SR": "CRAS São Rafael",
        "SD": "CRAS Selmi Dei",
        "VS": "CRAS Vale do Sol",
        "VV": "CRAS Valle Verde",
        "YO": "CRAS Yolanda Ópice",
    },
    "especial": {
        "C. Pop": "Centro Pop",
        "CAsa de Acolhida": "Casa de Acolhida",
        "RI": "Residência Inclusiva",
        "C Dia": "Centro Dia do Idoso",
        "Promaip F PI": "PROMAIP Feminino",
        "Promaip M": "PROMAIP Masculino",
        "Recanto Feliz": "República de Idosos Recanto Feliz",
        "Vila Dignidade": "República de Idosos Vila Dignidade",
    },
}

CAMPOS = {

    # ========================================================
    # CRAS - PROTEÇÃO SOCIAL BÁSICA
    # ========================================================
    "cras": {
        "nome": "CRAS (Proteção Básica)",
        "secoes": [
            ("I. Famílias Referenciadas na Unidade", [
                ("fam_cadastradas_total", "Nº de famílias cadastradas na unidade (ativos e inativos)"),
                ("fam_cadastradas_novas", "Nº de famílias cadastradas no mês - NOVAS FAMÍLIAS"),
                ("total_atendimentos_unidade", "Total de atendimentos na Unidade (recep., técnicos, Cad, entrega Pmais e CB)"),
                ("total_familias_atendidas", "Total de famílias atendidas"),
            ]),
            ("A. Volume de Famílias em Acompanhamento pelo PAIF - novas famílias", [
                ("paif_total_acompanhamento", "A.1. Total de famílias em acompanhamento pelo PAIF"),
                ("paif_novas_inseridas", "A.2. Novas famílias inseridas no acompanhamento do PAIF durante o mês de referência"),
                ("paif_atendidas_mes", "Famílias em acompanhamento atendidas no mês"),
                ("paif_com_paf", "Famílias em acompanhamento com PAF"),
            ]),
            ("B. Perfil das Famílias Acompanhadas - Todas as famílias", [
                ("perfil_extrema_pobreza", "B.1. Famílias em situação de extrema pobreza (R$109,00)"),
                ("perfil_bolsa_familia", "B.2. Famílias beneficiárias do Programa Bolsa Família"),
                ("perfil_bf_descumprimento", "B.3. Famílias beneficiárias do Programa BF em descumprimento de condicionalidades"),
                ("perfil_bpc", "B.4. Famílias com membros beneficiários do BPC"),
                ("perfil_trabalho_infantil", "B.5. Famílias com crianças ou adolescentes em situação de trabalho infantil"),
                ("perfil_servico_acolhimento", "B.6. Famílias com crianças ou adolescentes em Serviço de Acolhimento"),
                ("perfil_isolamento", "Nº de famílias acompanhadas com pessoas em isolamento"),
                ("perfil_situacao_rua", "Nº de famílias acompanhadas com pessoas em situação de rua"),
                ("perfil_mse", "Nº de famílias com adolescentes em cumprimento de MSE"),
                ("perfil_acolhimento_criancas", "Nº de famílias acompanhadas com crianças e adolescentes - acolhimento"),
                ("perfil_violacao_direitos", "Nº de famílias com indícios de violação de direitos"),
                ("perfil_peti", "Nº de famílias  acompanhadas com crianças e adolescentes - PETI"),
                ("perfil_descumprimento_recorrente", "Descumprimento de condicionalidade recorrente"),
                ("perfil_evasao_escolar", "Evasão escolar"),
                ("perfil_pcd", "PCD não inserido em instituição escolar ou rede de atendimento"),
                ("perfil_conflito_familiar", "Conflito familiar"),
                ("perfil_substancia_psicoativa", "Nº de famílias com usuários de substância psicoativa"),
                ("perfil_transtorno_mental", "Nº de famílias com membros com transtorno mental"),
                ("perfil_privacao_liberdade", "Nº de famílias com membros em privação de liberdade"),
                ("perfil_acamados", "Nº de famílias com integrantes acamados ou sérios problemas de saúde"),
                ("perfil_pmais", "Nº de famílias beneficiárias do programa PMAIS"),
                ("perfil_prog_municipais", "Nº de famílias beneficiárias de Prog. Sociais Municipais (PIIS / Bolsa Cidadania e Filhos do Sol, Locação Social)"),
                ("perfil_bpc_id_pcd", "Nº de famílias com membros beneficiários do BPC - ID e/ou PCD"),
                ("perfil_jovem_cidadao", "Jovens inscritos no Programa Jovem Cidadão com vulnerabilidade social"),
            ]),
            ("C. Volume de Atendimentos no CRAS", [
                ("atd_particularizado", "Atendimento particularizado no CRAS"),
                ("visitas_domiciliares", "C.6. Visitas domiciliares realizadas (atendimento part. no domicílio)"),
                ("atd_coletivo", "Atendimento coletivo"),
                ("atd_particularizados_total", "C.1. Total de atendimentos particularizados realizados (soma dos dois primeiros)"),
                ("atd_equipe_tecnica", "Total de atendimentos realizados pela equipe técnica no CRAS"),
                ("busca_ativa", "Nº de buscas ativas realizadas"),
                ("cadunico_inclusoes", "C.2. Nº de inclusões no Cadastro Único"),
                ("cadunico_atualizacoes", "C.3. Nº de atualizações do Cadastro Único"),
            ]),
            ("Encaminhamentos", [
                ("enc_cursos", "Nº de encaminhamentos para cursos profissionalizantes e mercado de trabalho"),
                ("enc_rede_privada", "Nº de encaminhamentos para a Rede Socioassistencial Privada"),
                ("enc_pse", "Nº de encaminhamentos para a PSE (exceção CREAS)"),
                ("enc_setor_cadunico", "Nº de encaminhamentos para setor do Cadastro Único"),
                ("enc_programas_socioassistenciais", "Nº de encaminhamento para inserção em programas socioassistenciais (VL, BC, PIIS, FS)"),
                ("enc_fundo_social", "Nº de encaminhamento para o Fundo Social de Solidariedade"),
                ("enc_outras_politicas", "Nº de encaminhamentos para Outras Políticas Públicas"),
                ("enc_defesa_direitos", "Nº de encaminhamentos para o Sistema de Defesa de Direitos (CT, MP, Defesoria)"),
                ("enc_outros_locais", "Nº de encaminhamentos para outros locais/serviços (Cartórios, Poupatempo)"),
                ("enc_bpc", "C.4. Indivíduos encaminhados para acesso ao BPC"),
                ("enc_creas", "C.5. Famílias encaminhadas para o CREAS"),
            ]),
            ("Benefícios Eventuais", [
                ("benef_auxilio_funeral", "C.8. Total de auxílios-funeral concedidos/entregues durante o mês de referência"),
                ("benef_cesta_basica", "Nº de concessões de cesta básica"),
                ("benef_vale_transporte", "Nº de concessões de vale transporte"),
                ("benef_segunda_via", "Nº de concessões de 2ª via de documentos - certidões"),
                ("benef_outros", "C.9. Outros benefícios eventuais concedidos/entregues durante o mês de referência (soma dos dados anteriores com exceção do Auxílio Funeral)"),
            ]),
            ("Programas Sociais", [
                ("prog_paa_familias", "Nº de famílias atendidas (mês) do PAA"),
                ("prog_paa_alimentos", "Nº de concessões de alimentos na semana do PAA"),
                ("prog_piis", "Nº de pessoas do território ativas no programa atendidas/acompanhadas no mês do PIIS"),
                ("prog_bolsa_cidadania", "Nº de pessoas do território ativas no programa atendidas/acompanhadas no mês do Programa Bolsa Cidadania"),
                ("prog_filhos_sol", "Nº de pessoas do território ativas no programa atendidas/acompanhadas no mês do Programa Filhos do Sol"),
                ("prog_bolsa_familia", "Nº de pessoas do território ativas no programa atendidas/acompanhadas no mês do Programa Bolsa Família"),
                ("prog_bf_descumprimento", "Nº de famílias atendidas no mês em descumprimento de condicionalidades do Programa Bolsa Família"),
                ("prog_bpc", "Nº de pessoas beneficiárias atendidas/acompanhadas no mês do BPC"),
                ("prog_outros", "Nº de pessoas do território ativas no programa atendidas/acompanhadas no mês de outros programas socioassistenciais municipais"),
            ]),
            ("D. Atendimentos Coletivos (Grupos/SCFV)", [
                ("grupos_paif_participantes", "Nº total de participantes nos grupos no mês/PAIF"),
                ("grupos_0_6", "Nº total de participantes nos grupos no mês/ 0 a 6"),
                ("grupos_0_6_total", "Total de grupos"),
                ("grupos_7_14", "Nº total de participantes nos grupos no mês/ 7 a 14"),
                ("grupos_7_14_total", "Total de grupos"),
                ("grupos_15_17", "Nº total de participantes nos grupos no mês/ 15 a 17"),
                ("grupos_15_17_total", "Total de grupos"),
                ("grupos_18_59", "Nº total de participantes nos grupos no mês/ 18 a 59"),
                ("grupos_18_59_total", "Total de grupos"),
                ("grupos_idosos", "Nº total de participantes nos grupos no mês/idosos"),
                ("grupos_idosos_total", "Total de grupos"),
                ("grupos_palestras", "Nº total de participantes nos grupos no mês/ palestras, oficinas e atividades coletivas não continuadas"),
                ("grupos_pcd", "Nº total de participantes nos grupos no mês/PCD"),
            ]),
            ("XII. Oficinas Realizadas em Parcerias", [
                ("oficinas_esporte", "Nº de oficinas realizadas em parceria com Esporte (modalidade)"),
                ("oficinas_cultura", "Nº de oficinas realizadas em parceria com a Cultura (oficinas)"),
                ("oficinas_seg_alimentar", "Nº de oficinas realizadas em parceria com a Coord. de Segurança Alimentar"),
                ("oficinas_trabalho", "Nº de oficinas realizadas em parceria com Trabalho e Desenvolvimento Econômico (Bolsa Cidadania)"),
                ("oficinas_outras", "Outras Oficinas"),
            ]),
            ("Bloco V - Territórios em Rede", [
                ("territorio_projetos", "Total de projetos/ações coletivas realizadas no território (Prefeitura nos Bairros, OP, Campanhas, etc)"),
                ("territorio_reunioes", "Reuniões intersetoriais, estudos de caso e mobilizações da rede"),
            ]),
            ("Bloco VI - Outras Ações", [
                ("outras_relatorios", "Nº de relatórios técnicos elaborados"),
                ("outras_conselho_gestor", "Nº de reuniões do Conselho Gestor"),
                ("outras_reunioes_internas", "Nº de reuniões internas na unidade"),
                ("outras_capacitacoes", "Nº de funcionários que participaram de capacitações"),
            ]),
            ("Bloco VI - Vulnerabilidades do Território ('1 para SIM e 0 ou VAZIO para NÃO')", [
                ("vuln_evasao_escolar", "Evasão escolar"),
                ("vuln_dependencia_quimica", "Dependência Química"),
                ("vuln_negligencias_criancas", "Negligências com crianças"),
                ("vuln_negligencias_idosos", "Negligências/ abandono de idosos"),
                ("vuln_isolamento", "Pessoas em isolamento"),
                ("vuln_moradias_irregulares", "Moradias irregulares/ submoradia"),
                ("vuln_violencia_domestica", "Violência doméstica/ intrafamiliar"),
                ("vuln_criminalidade", "Altos índices de criminalidade/ Violência urbana"),
                ("vuln_situacao_rua", "Pessoas em situação de rua"),
                ("vuln_despejo", "Despejo e/ou solicitação de Locação Social"),
                ("vuln_acessibilidade", "Não acesso aos serviços devido à falta de acessibilidade"),
                ("vuln_acamadas", "Pessoas acamadas ou com sérios problemas de saúde"),
                ("vuln_dificuldade_acesso", "Pessoas com dificuldade de acesso (inserção) em outras políticas públicas"),
                ("vuln_conflitos_familiares", "Conflitos familiares"),
                ("vuln_trabalho_infantil", "Trabalho infantil"),
                ("vuln_exploracao_sexual", "Exploração sexual de crianças e adolescentes"),
                ("vuln_trabalho_sexual", "Trabalho sexual de adultos"),
                ("vuln_trafico", "Tráfico de drogas"),
                ("vuln_agua_luz", "Água e luz cortada"),
                ("vuln_outras", "Outras vulnerabilidades"),
            ]),
        ],
    },

    # ========================================================
    # CASA DE ACOLHIDA - PROTEÇÃO SOCIAL ESPECIAL
    # ========================================================
    "acolhida": {
        "nome": "Casa de Acolhida (PSE)",
        "secoes": [
            ("Dados Gerais", [
                ("total_atendimentos_mes", "Total de atendimentos no mês"),
                ("total_passagens", "Total de passagens fornecidas"),
                ("total_pernoites", "Total de pernoite (Casa de acolhida)"),
                ("total_refeicoes", "Total de refeições fornecidas"),
                ("atd_recepcao", "Atendimentos realizados pela recepção"),
                ("atd_abordagem", "Atendimentos realizados pela equipe de abordagem"),
                ("atd_equipe_tecnica", "Atendimentos realizados pela equipe técnica"),
                ("atd_nao_preconizados", "Atendimentos não preconizados"),
            ]),
            ("Perfil População de Rua (Munícipes)", [
                ("mun_0_12", "0 a 12 anos"),
                ("mun_13_17", "13 a 17 anos"),
                ("mun_18_39", "18 a 39 anos"),
                ("mun_40_59", "40 a 59 anos"),
                ("mun_60_mais", "60 anos ou mais"),
                ("mun_masculino", "Masculino"),
                ("mun_feminino", "Feminino"),
                ("total_pessoas_rua_atendidas", "Total de pessoas em situação de rua atendidas"),
                ("tempo_ate_3_meses", "Até 3 meses"),
                ("tempo_3m_1_ano", "De 3 meses até 1 ano"),
                ("tempo_1_5_anos", "De 1 ano até 5 anos"),
                ("tempo_acima_5_anos", "Acima de 5 anos"),
                ("mun_cor_branca", "Branca"),
                ("mun_cor_parda", "Parda"),
                ("mun_cor_negra", "Negra"),
                ("mun_cor_indigena", "Indigena"),
                ("mun_cor_amarela", "Amarela"),
            ]),
            ("Perfil População Itinerante", [
                ("itin_0_12", "0 a 12 anos"),
                ("itin_13_17", "13 a 17 anos"),
                ("itin_18_39", "18 a 39 anos"),
                ("itin_40_59", "40 a 59 anos"),
                ("itin_60_mais", "60 anos ou mais"),
                ("itin_masculino", "Masculino"),
                ("itin_feminino", "Feminino"),
                ("itinerantes_atendidos", "Itinerantes atendidos"),
                ("itin_cor_branca", "Branca"),
                ("itin_cor_parda", "Parda"),
                ("itin_cor_negra", "Negra"),
                ("itin_cor_indigena", "Indigena"),
                ("itin_cor_amarela", "Amarela"),
                ("trecho_ate_3_meses", "até 3 meses"),
                ("trecho_mais_3_meses", "mais de 3 meses"),
                ("trecho_mais_1_ano", "mais de 1 ano"),
                ("trecho_mais_5_anos", "mais de 5 ano"),
            ]),
            ("Fornecimento de Passagem (cidades)", [
                ("pass_barretos", "Barretos"),
                ("pass_bauru", "Bauru"),
                ("pass_campinas", "Campinas"),
                ("pass_jaboticabal", "Jaboticabal"),
                ("pass_jau", "Jaú"),
                ("pass_matao", "Matão"),
                ("pass_ribeirao_preto", "Ribeirão Preto"),
                ("pass_rio_claro", "Rio Claro"),
                ("pass_sao_carlos", "São carlos"),
                ("pass_sj_rio_preto", "Sâo José do Rio Preto"),
                ("pass_sao_paulo", "São Paulo"),
            ]),
        ],
    },

    # ========================================================
    # CENTRO POP - PROTEÇÃO SOCIAL ESPECIAL
    # ========================================================
    "centro_pop": {
        "nome": "Centro Pop (PSE)",
        "secoes": [
            ("Dados Gerais", [
                ("total_atendimentos_mes", "Total de atendimentos no mês (CP)"),
                ("total_passagens", "Total de passagens fornecidas"),
                ("total_refeicoes", "Total de refeições fornecidas"),
                ("pessoas_rua_atendidas", "Pessoas em situação de rua atendidas"),
                ("itinerantes_atendidos", "Itinerantes atendidos"),
                ("atd_recepcao", "Realizados pela recepção"),
                ("atd_abordagem", "Realizados pela equipe de abordagem"),
                ("atd_equipe_tecnica", "Realizados pela equipe técnica"),
                ("atd_nao_preconizados", "Não preconizados pelo serviço"),
            ]),
            ("Perfil População de Rua (Munícipes)", [
                ("rua_0_12", "0 a 12 anos"),
                ("rua_13_17", "13 a 17 anos"),
                ("rua_18_39", "18 a 39 anos"),
                ("rua_40_59", "40 a 59 anos"),
                ("rua_60_mais", "60 anos ou mais"),
                ("rua_masculino", "Masculino"),
                ("rua_feminino", "Feminino"),
            ]),
            ("Perfil População Itinerante", [
                ("itin_0_12", "0 a 12 anos"),
                ("itin_13_17", "13 a 17 anos"),
                ("itin_18_39", "18 a 39 anos"),
                ("itin_40_59", "40 a 59 anos"),
                ("itin_60_mais", "60 anos ou mais"),
                ("itin_masculino", "Masculino"),
                ("itin_feminino", "Feminino"),
            ]),
            ("Perfil População Abordada", [
                ("abord_masculino", "Masculino"),
                ("abord_feminino", "Feminino"),
            ]),
            ("Fornecimento de Passagem (cidades)", [
                ("pass_barretos", "Barretos"),
                ("pass_bauru", "Bauru"),
                ("pass_campinas", "Campinas"),
                ("pass_jaboticabal", "Jaboticabal"),
                ("pass_jau", "Jaú"),
                ("pass_matao", "Matão"),
                ("pass_ribeirao_preto", "Ribeirão Preto"),
                ("pass_rio_claro", "Rio Claro"),
                ("pass_sao_carlos", "São Carlos"),
                ("pass_sj_rio_preto", "Sâo José do Rio Preto"),
                ("pass_sao_paulo", "São Paulo"),
            ]),
            ("Serviço de Abordagem Social", [
                ("abord_pessoa_rua", "Pessoa em situação de rua"),
                ("abord_migrantes", "Migrantes / itinerantes"),
                ("abord_idosos", "Idosos"),
                ("abord_imigrantes", "Imigrantes de outros países/ refugiados"),
                ("abord_pcd", "PCD"),
                ("abord_criancas", "Crianças e adolescentes"),
                ("abord_usuarios_spa", "Usuários de SPA"),
                ("abord_transtorno_masc", "Pessoa com transtorno mental - sexo masculino"),
                ("abord_transtorno_fem", "Pessoa com transtorno mental-  sexo feminino"),
                ("abord_casais_familias", "Casais ou famílias em situação de rua"),
                ("abord_total_pessoas_mes", "Número de pessoas abordadas no mês"),
                ("abord_mendicancia_residencia", "Pessoa em medicância com residência fixa"),
                ("abord_desorientada", "Pessoa desorientada (demência, alzheimer, transtorno mental) com residência fixa"),
                ("abord_spa_local_publico", "Pessoa fazendo uso de SPA em local público (habito de rua)"),
                ("abord_imigrante_refugiado", "Imigrante de outros países/ refugiado"),
                ('abord_trabalho_rua', 'Pessoa que sobrevive do "trabalho de rua"  ( venda, malabaris, artesanatos)'),
                ("abord_idoso_mendicancia", "Idoso em situação de mendicância com residência fixa"),
                ("abord_pcd_mendicancia", "PCD em situação de mendicância com residência fixa"),
                ("abord_exploracao_sexual", "Adolescente em situação de exploração sexual"),
                ("abord_trabalho_infantil", "Criança e adolescente em situação de trabalho infantil"),
                ("abord_criancas_spa", "Criança e adolescente usuárias de SPA"),
                ("abord_outros", "Outros"),
                ("abord_total_abordagens", "Total de abordagens no mês"),
            ]),
        ],
    },

    # ========================================================
    # PROMAIP - PROTEÇÃO SOCIAL ESPECIAL
    # ========================================================
    "promaip": {
        "nome": "PROMAIP (PSE)",
        "secoes": [
            ("Acolhimento - Dados Gerais", [
                ("acolhimento_total", "Nº de crianças/adolescentes em acolhimento - total"),
                ("acolhimento_fem", "Nº de crianças/adolescentes em acolhimento -  (FEM)"),
                ("acolhimento_mas", "Nº de crianças/adolescentes em acolhimento -   (MAS)"),
                ("visitas_domiciliares", "Nº de visitas domiciliares realizadas"),
                ("relatorios_elaborados", "Nº de relatórios elaborados"),
                ("passeios_atividades", "Nº de passeios / atividades externas"),
                ("familia_nuclear", "Nº de atendimentos à família Nuclear"),
                ("familia_extensa", "Nº de atendimentos à família Extensa"),
                ("familia_substituta", "Nº de atendimentos à família Substituta"),
            ]),
            ("Articulação e Encaminhamentos", [
                ("enc_creas", "articulação e encaminhamentos e atendimentos (referente a criança acolhida) contrareferencia no CREAS"),
                ("enc_cras", "articulação e encaminhamentos e atendimentos (referente a criança acolhida) contrareferencia no CRAS/ PSB"),
                ("enc_programas", "articulação e encaminhamentos e atendimentos (referente a criança acolhida) Programas"),
                ("enc_rede_privada", "articulação e encaminhamentos e atendimentos (referente a criança acolhida) Rede socioassistencial privada"),
                ("enc_saude", "articulação e encaminhamentos e atendimentos (referente a criança acolhida) Unidades Sec. Municipal de Saúde"),
                ("enc_educacao", "articulação e encaminhamentos e atendimentos (referente a criança acolhida) Unidades Sec. Municipal de Educação"),
                ("enc_outras_politicas", "articulação e encaminhamentos e atendimentos (referente a criança acolhida) Outras políticas públicas"),
            ]),
            ("Perfil Etário", [
                ("idade_0_1", "00 a 01 ano"),
                ("idade_2_6", "02 a 06 anos"),
                ("idade_7_11", "07 a 11 anos"),
                ("idade_12_18", "12 a 18 anos"),
            ]),
            ("Tempo de Permanência", [
                ("tempo_menos_1_mes", "menos de 1 mês"),
                ("tempo_1_3_meses", "de 1 a 3 meses"),
                ("tempo_4_6_meses", "4 meses a 6 meses"),
                ("tempo_7m_1_ano", "7 meses a 1ano"),
                ("tempo_1_2_anos", "de 1 a 2 anos"),
                ("tempo_2_5_anos", "de 2 a 5 anos"),
                ("tempo_acima_5_anos", "Acima de 5 anos"),
            ]),
            ("Vulnerabilidades das Crianças/Adolescentes", [
                ("vuln_deficiencia", "Nº de crianças/adolescentes com deficiência"),
                ("vuln_transtorno_psiquiatrico", "Nº de crianças/adolescentes com transtorno psiquiátrico"),
                ("vuln_ameaca_morte", "Nº de crianças/adolescentes em situação de ameaça de morte"),
                ("vuln_dependencia_quimica", "Nº de crianças/adolescentes com dependência química"),
                ("vuln_lgbtqia", "Nº de LGBTQIA+"),
                ("vuln_mse_meio_aberto", "Nº de adolescentes em cumprimento de MSE em meio aberto"),
                ("vuln_outras", "Outras Vulnerabilidades"),
            ]),
            ("Outras Informações", [
                ("info_transferencia_renda", "Adolescentes em programa de transferencia de renda municipal (FS, BF)"),
                ("info_internacao_drogadicao", "Adolescentes em internação para tratamento de drogadição"),
            ]),
            ("Acolhidos no Mês (Relatório Comunicação)", [
                ("acolhidos_mes_0_1", "00 a 01 ano"),
                ("acolhidos_mes_2_6", "02 a 06 anos"),
                ("acolhidos_mes_7_11", "07 a 11 anos"),
                ("acolhidos_mes_12_17", "12 a 17 anos"),
                ("acolhidos_1o_acolhimento", "1º acolhimento"),
                ("acolhidos_reincidencia", "reincidência"),
                ("acolhidos_transferidos", "transferidos de outras unidades de acolhimento"),
                ("acolhidos_outros_municipios", "oriundos de outros municípios"),
            ]),
            ("Situação de Violação (acolhidos no mês)", [
                ("violacao_sexual", "Situação de violência sexual"),
                ("violacao_fisica", "Situação de violência física"),
                ("violacao_negligencia", "Situação de negligência"),
                ("violacao_trabalho_infantil", "Situação de Trabalho Infantil"),
                ("violacao_outras", "Outros tipos de violência/violações de direitos"),
            ]),
            ("Desligamentos (ocorrido no mês)", [
                ("deslig_familia_extensa", "Nº de crianças e adolescentes - Retorno à família - extensa"),
                ("deslig_familia_nuclear", "Nº de crianças e adolescentes - Retorno à família - nuclear"),
                ("deslig_guarda_adocao", "Nº de crianças e adolescentes - Guarda / Adoção"),
                ("deslig_rede_privada", "Nº de crianças e adolescentes - Encaminhado(a) à unidade da Rede Privada"),
                ("deslig_18_anos", "Foram desligados por completarem 18 anos"),
            ]),
        ],
    },

    # ========================================================
    # REPÚBLICA DE IDOSOS - PROTEÇÃO SOCIAL ESPECIAL
    # ========================================================
    "republica_idosos": {
        "nome": "República de Idosos (PSE)",
        "secoes": [
            ("Dados Gerais (Mensais)", [
                ("capacidade_total_moradias", "Capacidade de atendimento total (total de moradias)"),
                ("moradias_aptas", "Moradias aptas para ocupação"),
                ("moradias_ocupadas", "Total de moradias ocupadas"),
                ("total_idosos_residentes", "Total de idosos residentes"),
                ("idosos_sexo_masculino", "Idosos residentes do sexo masculino"),
                ("idosos_sexo_feminino", "Idosos residentes do sexo feminino"),
                ("idosos_inseridos_mes", "Nº de pessoas idosas inseridas, durante o mês de referência"),
                ("idosos_desligados_mes", "Nº de pessoas idosas desligadas, durante o mês de referência"),
                ("idosos_afastados_saude", "Nº de pessoas idosas afastadas para tratamento de saúde"),
                ("idosos_lista_espera", "Nº de pessoas idosas em lista de espera"),
                ("solicitacoes_vaga_mes", "Nº solicitações de vagas no mês"),
                ("solicitacoes_fora_criterios", "Nº vagas solicitadas no mês fora dos critérios do Serviço"),
            ]),
            ("Atendimentos Individualizados", [
                ("atd_particularizado_idosos", "Nº de atendimento particularizado com idosos"),
                ("acompanhamento_unidade_saude", "Nº de acompanhamento da pessoa idosa em unidade de saúde para tratamento"),
                ("acompanhamento_externo", "Nº de acompanhamento da pessoa idosa em outro atendimento externo (doc, inss)"),
                ("visitas_hospital", "Nº de visitas a hospital realizada ao idoso"),
                ("visitas_insercao", "Nº de visitas realizada para inserção do usuário ao serviço"),
                ("visitas_domiciliares_familia", "Nº de visitas domiciliares a família do idoso inserido no serviço"),
                ("atd_familia_morador", "Nº de atendimentos com  a família do morador"),
                ("intercorrencias_policia", "Nº de intercorrências com polícia / guarda municipal"),
                ("relatorios_tecnicos", "Nº de relatórios técnicos elaborado"),
            ]),
            ("Encaminhamentos de Idosos", [
                ("enc_prot_basica", "Proteção Social Básica (B.E. , doc)"),
                ("enc_prot_especial", "Proteção Social Especial"),
                ("enc_cadunico", "Inserção ou atualização do Cad. Único"),
                ("enc_rede_privada", "Rede Socioassistencial Privada"),
                ("enc_orgao_defesa", "Órgão de Defesa de Direitos"),
                ("enc_outras_politicas", "Outras Políticas Públicas"),
            ]),
            ("Articulações", [
                ("articulacao_prot_basica", "Proteção Social Básica"),
                ("articulacao_prot_especial", "Proteção Social Especial"),
                ("articulacao_rede_privada", "Rede Socioassistencial Privada"),
                ("articulacao_orgao_defesa", "Órgão de Defesa de Direitos"),
                ("articulacao_outras_politicas", "Outras Políticas Públicas"),
                ("capacitacoes_equipe", "Número de capacitações da equipe"),
            ]),
            ("Atendimentos Grupais", [
                ("atividades_externas", "Nº de atividades externas realizadas com os usuários"),
                ("palestras_encontros", "Nº de palestras/ encontros temáticos para os usuários"),
                ("reunioes_moradores", "Nº de reuniões com os moradores idosos  visando o planejamento e organização da rotina da unidade"),
                ("idosos_participantes_grupos", "Nº de idosos participantes dos grupos"),
                ("oficinas_esporte", "Articulação com Esporte"),
                ("oficinas_cultura", "Articulação com Cultura"),
                ("oficinas_outras", "Articulação com outras áreas"),
                ("participantes_esporte", "Articulação com Esporte"),
                ("participantes_cultura", "Articulação com Cultura"),
                ("participantes_outras", "Articulação com outras áreas"),
                ("comemoracoes", "Nº de comemorações realizadas"),
            ]),
            ("Características dos Usuários (Semestral)", [
                ("benef_pbf", "Nº de idosos beneficiários do PBF"),
                ("benef_bpc", "Nº de idosos beneficiários do BPC"),
                ("benef_pensao_aposentadoria", "Nº de idosos beneficiários de pensão ou aposentadoria"),
                ("sem_beneficios", "Nº de idosos sem benefícios"),
                ("benef_prog_seg_alimentar", "Nº de idosos beneficiários de Prog. Municipais de Seg. Alimentar"),
                ("benef_outros_prog_municipais", "Nº de idosos beneficiários de outros Prog. Municipais (PIIS / BC)"),
                ("possuem_cadunico", "Nº de idosos que possuem Cadastro Único"),
                ("idosos_deficiencia", "Nº de idosos com deficiência"),
                ("idosos_doenca_mental", "Nº de idosos com doença mental"),
                ("idosos_dependencia_quimica", "Nº de idosos com dependência química"),
                ("hist_violencia", "Nº de idosos com histórico de violência"),
                ("hist_negligencia_abandono", "Nº de idosos com histórico de negligência, abandono e isolamento"),
                ("vinculos_fragilizados", "Nº de Idosos com vínculos familiares fragilizados (possuem contato com parentes)"),
                ("vinculos_rompidos", "Nº de idosos com vínculos familiares rompidos ou sem familiares no município"),
            ]),
            ("Situação de Renda", [
                ("renda_ausencia", "Idosos com ausência de remuneração (renda R$0,00)"),
                ("renda_inferior_1_sm", "Com renda inferior a 1 s.m."),
                ("renda_1_a_1e5_sm", "Com renda per capta de 1 s.m. a 1 e1/2  s.m"),
                ("renda_acima_1e5_sm", "Acima de 1 e 1/2 s.m"),
            ]),
            ("Faixa Etária", [
                ("idade_60_64", "Nº de pessoas idosas entre 60 a 64 anos"),
                ("idade_65_69", "Nº de pessoas idosas entre 65 a 69 anos"),
                ("idade_70_79", "Nº de pessoas idosas entre 70 a 79 anos"),
                ("idade_80_89", "Nº de pessoas idosas entre 80 a 89 anos"),
                ("idade_90_mais", "Nº de pessoas idosas acima de 90 anos"),
            ]),
        ],
    },

    # ========================================================
    # RESIDÊNCIA INCLUSIVA - PROTEÇÃO SOCIAL ESPECIAL
    # ========================================================
    "residencia_inclusiva": {
        "nome": "Residência Inclusiva (PSE)",
        "secoes": [
            ("Dados Gerais", [
                ("total_acolhidas", "Total mulheres acolhidas"),
                ("novos_abrigamentos_mes", "Novos abrigamentos no mês"),
                ("desligamentos", "Desligamentos"),
                ("espera_vagas", "Espera por vagas"),
                ("atendimentos_familia", "nº de atendimentos à família/ recebimento da família na unidade"),
            ]),
            ("Atividades / Ações Realizadas", [
                ("visitas_domiciliares", "Nº de visitas domiciliares realizadas"),
                ("relatorios_elaborados", "Nº de relatórios elaborados"),
                ("reunioes_usuarios", "Nº de reuniões com os usuários para planejamento ou organização da unidade"),
                ("enc_orgao_defesa", "Órgão de defesa de direito"),
                ("enc_unidades_saude", "Unidades Sec. Municipal de Saúde"),
                ("enc_outras_politicas", "Outras políticas públicas"),
            ]),
            ("Perfil Etário", [
                ("idade_18_29", "18 a 29 anos"),
                ("idade_30_39", "30 a 39"),
                ("idade_40_49", "40 a 49"),
                ("idade_50_59", "50 a 59 anos"),
            ]),
            ("Tempo de Permanência", [
                ("tempo_menos_6_meses", "Menos de 6 meses"),
                ("tempo_7_meses_3_anos", "7 meses a 3 anos"),
                ("tempo_3_anos_mais", "3 anos +"),
            ]),
            ("Tipos de Deficiência", [
                ("def_fisica", "Deficiência física"),
                ("def_cognitiva_mental", "Deficiência Cognitiva/ mental"),
                ("def_baixa_visao", "Baixa visão"),
                ("def_cegueira", "Cegueira"),
                ("def_surdez_leve", "Surdez leve"),
                ("def_surdez_moderada", "Surdez moderada"),
                ("def_surdez_severa", "Surdez severa"),
            ]),
            ("Usuários Inseridos na Rede", [
                ("rede_caps_ii", "Caps II"),
                ("rede_caps_ad", "Caps Ad"),
                ("rede_cras", "Crasma"),
                ("rede_centro_reabilitacao", "Centro de reabilitação"),
                ("rede_centro_dia_pcd", "Centro Dia Pessoa Com Deficiência"),
                ("rede_cursos_capacitacao", "Inseridos em Cursos de Capacitação"),
                ("rede_mercado_trabalho", "Inseridos no mercado de trabalho"),
            ]),
            ("Vulnerabilidades", [
                ("usuarios_spa", "Usuários de SPA"),
                ("usuarios_transtorno_mental", "Transtorno mental"),
                ("independentes_sem_ajuda", "Pessoas independentes sem ajuda de equipamentos"),
                ("independentes_com_ajuda", "Pessoas independentes com ajuda de equipamentos"),
                ("comprometimento_avd", "Pessoas com comprometimento de atividades de vida diária"),
                ("medicamento_continuo", "Pessoas com necessidade de uso de medicamento contínuo"),
            ]),
            ("Outras Informações", [
                ("usuarios_bpc_deficiente", "Nº de usuários com BPC deficiênte"),
                ("usuarios_aposentadoria_pensao", "Nº de usuários com aposentadoria ou pensão"),
                ("acolhidos_contatos_familiares", "nº de acolhidos com contatos familiares"),
                ("internados_tratamento_saude", "Usuários internados para tratamento de saúde"),
            ]),
            ("Novos Acolhimentos", [
                ("novos_encaminhado_rede", "Encaminhado pela rede"),
                ("novos_encaminhado_defesa", "Encaminhado pelo Sistema de defesa de Direitos"),
            ]),
        ],
    },

    # ========================================================
    # CENTRO DIA DO IDOSO - PROTEÇÃO SOCIAL ESPECIAL
    # ========================================================
    "centro_dia_idoso": {
        "nome": "Centro Dia do Idoso (PSE)",
        "secoes": [
            ("Dados Mensais de Atendimento", [
                ("idosos_masculino", "Sexo masculino"),
                ("idosos_feminino", "Sexo feminino"),
                ("idosos_aguardando_vagas", "Idosos aguardando vagas"),
                ("atd_part_familias", "Atendimentos particularizados com as famílias"),
                ("atd_part_idosos_tecnico", "Atendimentos pela equipe técnica e apoio"),
                ("atd_part_idosos_enfermagem", "Atendimentos pela equipe de enfermagem"),
                ("visitas_domiciliares", "Nº de visitas domiciliares"),
            ]),
            ("Grupos (Nº de Encontros)", [
                ("enc_fisica", "Grupos de Atividade física"),
                ("enc_estimulacao", "Grupos de Estimulação cognitiva"),
                ("enc_roda_conversa", "Grupos de Roda de conversa"),
                ("enc_musica", "Grupos de Música"),
                ("enc_artesanato", "Grupos de Oficina - Artesanato"),
                ("enc_palestras", "Nº de palestras para de pessoas idosas"),
                ("enc_atividades_externas", "Nº de atividade externas"),
                ("enc_socioculturais", "Atividades socioculturais"),
                ("enc_outras_atividades", "Outras atividades - eventos e ativ. comunitárias"),
            ]),
            ("Grupos (Nº de Participantes)", [
                ("part_fisica", "Grupos de Atividade física"),
                ("part_estimulacao", "Grupos de Estimulação cognitiva"),
                ("part_roda_conversa", "Grupos de Roda de conversa"),
                ("part_musica", "Grupos de Música"),
                ("part_artesanato", "Grupos de Oficina - Artesanato"),
                ("part_palestras", "Nº de palestras para de pessoas idosas"),
                ("part_atividades_externas", "Nº de atividade externas"),
                ("part_socioculturais", "Atividades socioculturais"),
                ("part_outras_atividades", "Outras atividades - eventos e ativ. comunitárias"),
            ]),
            ("Forma de Acesso (inseridos no mês)", [
                ("acesso_procura_espontanea", "Procura Espontânea"),
                ("acesso_psb", "Proteção Social Básica"),
                ("acesso_pse", "Proteção Social Especial"),
                ("acesso_judiciario", "Judiciário"),
                ("acesso_busca_ativa", "Busca Ativa"),
                ("acesso_saude", "Saúde"),
                ("acesso_outros", "Outros"),
            ]),
            ("Encaminhamentos", [
                ("enc_psb", "Proteção Social Básica"),
                ("enc_pse", "Proteção Social Especial"),
                ("enc_rede_privada", "Rede socioassistencial privada"),
                ("enc_orgao_defesa", "Órgão de defesa de direito"),
                ("enc_outras_politicas", "Outras políticas públicas"),
                ("enc_unidades_saude", "Unidades Sec. Municip. de Saúde"),
                ("enc_bpc", "Nº de encaminhamento para BPC"),
                ("enc_cadunico", "Nº de encaminhamento para Cadastro Único"),
                ("enc_beneficios_eventuais", "Nº de pessoas idosas encaminhados para benefícios eventuais"),
                ("enc_acolhimento", "Nº de pessoas idosas encaminhados para acolhimento"),
            ]),
            ("Outras Ações", [
                ("relatorios_elaborados", "Nº de relatórios elaborados"),
                ("reunioes_planejamento", "Nº de reuniões com os de pessoas idosas/famílias para planejamento e organização da unidade"),
                ("refeicoes_fornecidas", "Nº de refeições fornecidas"),
                ("orgaos_parceiros", "Número de orgãos parceiros nas atividades em grupo (cultura, esporte, saúde,universidades, Sistema S)"),
            ]),
            ("Caracterização dos Usuários (Semestral)", [
                ("idosos_dependencia_grau_1_2", "Nº de pessoas idosas com grau de dependencia 1 e 2"),
                ("idosos_fora_perfil_grau_3", "Nº de pessoas idosas fora do perfil: grau de dependencia 3 ou Centro de Convivência"),
                ("idosos_pensao_aposentadoria", "Nº de pessoas idosas beneficiários de pensão ou aposentadoria"),
                ("idosos_bpc", "Nº de pessoas idosas beneficiários do BPC"),
                ("idosos_sem_beneficio", "Nº de pessoas idosas sem benefício"),
                ("idosos_violencia_uso_abusivo", "Nº de pessoas idosas cuja situação de violência esteja associada ao uso abusivo de substâncias psicoativas"),
                ("idosos_vitimas_violacao_intrafamiliar", "Nº de pessoas idosas vítimas de violação intra familiar"),
                ("idosos_vitimas_negligencia_abandono", "Nº de pessoas idosas vítimas de negligência / abandono"),
                ("idosos_isolamento_social", "Nº de pessoas idosas com vivência de isolamento social"),
                ("idosos_sem_vulnerabilidade", "Nº de pessoas idosas sem vulnerabilidade social e/ou situação de risco"),
                ("idosos_independentes_sem_ajuda", "Nº de pessoas idosas independentes - sem ajuda de equipamento"),
                ("idosos_independentes_com_ajuda", "Nº de pessoas idosas independentes - com ajuda de equipamento"),
                ("idosos_comprometimento_cognitivo", "Nº de pessoas idosas com comprometimento cognitivo"),
                ("idosos_comprometimento_fisico_motor", "Nº de pessoas idosas com comprometimento físico/ motor"),
                ("idosos_comprometimento_avd", "Nº de pessoas idosas com comprometimento de atividades de vida diária"),
            ]),
            ("Famílias Acompanhadas (Semestral)", [
                ("familias_creas", "Famílias acompanhadas pelo CREAS"),
                ("familias_cras", "Famílias acompanhadas pelo CRAS"),
                ("familias_mais_idosos", "Famílias  acompanhadas com mais de pessoas idosas"),
                ("familias_idosos_acolhimento", "Famílias  acompanhadas com de pessoas idosas em acolhimento"),
                ("familias_pcd", "Famílias  acompanhadas com PCD"),
                ("familias_indicios_violacao", "Famílias com indícios de violação de direitos"),
                ("familias_substancia_psicoativa", "Famílias com usuários de substância psicoativa"),
                ("familias_transtorno_mental", "Famílias com membros com transtorno mental"),
                ("familias_privacao_liberdade", "Famílias com membros em privação de liberdade"),
                ("familias_conflito_familiar", "Famílias com conflito familiar para cuidado do idoso"),
                ("familias_integrantes_acamados", "Famílias com integrantes acamados"),
                ("familias_sem_remuneracao", "Famílias com ausência de remuneração (renda R$0,00)"),
                ("familias_renda_ate_meio_sm", "Famílias com renda per capta entre R$1,00 e 1/2 s.m"),
                ("familias_renda_meio_a_1_sm", "Famílias com renda per capta entre 1/2 a 1 s.m"),
                ("familias_renda_acima_1_sm", "Famílias com renda per capita  familiar mensal acima de 1s.m"),
                ("familias_renda_principal_idoso", "Famílias cuja renda principal seja do idoso"),
                ("familias_inseridas_cadunico", "Famílias inseridas no Cadastro Único"),
                ("familias_benef_bolsa_familia", "Famílias beneficiárias do programa Bolsa Família"),
                ("familias_benef_programas_estaduais", "Famílias beneficiárias de programas estaduais"),
                ("familias_benef_programas_municipais", "Famílias beneficiárias de programas municipais"),
            ]),
            ("Faixa Etária (Semestral)", [
                ("idade_60_64", "Nº de pessoas idosas entre 60 a 64 anos"),
                ("idade_65_69", "Nº de pessoas idosas entre 65 a 69 anos"),
                ("idade_70_79", "Nº de pessoas idosas entre 70 a 79 anos"),
                ("idade_80_89", "Nº de pessoas idosas entre 80 a 89 anos"),
                ("idade_90_mais", "Nº de pessoas idosas acima de 90 anos"),
            ]),
            ("Transporte Utilizado (Semestral)", [
                ("transporte_veiculo_proprio", "Veículo próprio"),
                ("transporte_urbano", "Transporte urbano"),
                ("transporte_ajuda_terceiros", "Ajuda de terceiros"),
                ("transporte_outros_meios", "Outros meios"),
            ]),
            ("Motivo Solicitação de Vagas (Semestral)", [
                ("motivo_isolamento", "Convivência da pessoa idosa (isolamento)"),
                ("motivo_sem_condicoes_cuidador", "Família não possui condições de contratar um cuidador e necessita trabalhar"),
                ("motivo_sobrecarga_cuidados", "Família sobrecarregada nos cuidados das pessoas idosas"),
            ]),
            ("Motivo do Desligamento (Semestral)", [
                ("deslig_aumento_dependencia", "Aumento do grau de dependência"),
                ("deslig_desistencia", "Desistência por parte da pessoa idosa ou familiares"),
                ("deslig_obito", "Óbito"),
                ("deslig_indisponibilidade_familia", "Indisponibilidade da família ao levar o idoso"),
                ("deslig_outros", "Outros"),
            ]),
            ("Territorialização (Semestral)", [
                ("area_cras_cecap", "Área de abrangência: CRAS Cecap"),
                ("area_cras_cruzeiro_sul", "Área de abrangência: CRAS Cruzeiro do Sul"),
                ("area_cras_hortencias", "Área de abrangência: CRAS Hortências"),
                ("area_cras_pq_sao_paulo", "Área de abrangência: CRAS Pq São Paulo"),
                ("area_cras_yolanda_opice", "Área de abrangência: CRAS Yolanda Ópice"),
                ("area_cras_vale_do_sol", "Área de abrangência: CRAS Vale do Sol"),
                ("area_cras_maria_luiza", "Área de abrangência: CRAS Maria Luiza"),
                ("area_cras_valle_verde", "Área de abrangência: CRAS Valle Verde"),
                ("area_cras_sao_rafael", "Área de abrangência: CRAS São Rafael"),
                ("area_cras_selmi_dey", "Área de abrangência: CRAS Selmi Dey"),
                ("area_outras", "Outras áreas"),
            ]),
        ],
    },
}